// The LocationSerializer  below was generated by an artificial intelligence Model
package com.cs446g15.app.util

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import android.location.Location

@Serializer(forClass = Location::class)
object LocationSerializer : KSerializer<Location?> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Location", PrimitiveKind.STRING)

    // We currently only serialize the longitude and latitude but we can add additional fields from
    // the Location object as necessary
    override fun serialize(encoder: Encoder, value: Location?) {
        if (value == null) {
            encoder.encodeNull()
        } else {
            encoder.encodeString("${value.latitude},${value.longitude}")
        }
    }

    override fun deserialize(decoder: Decoder): Location? {
        val coordinates = decoder.decodeString().split(',')
        return if (coordinates.size == 2) {
            Location("").apply {
                latitude = coordinates[0].toDouble()
                longitude = coordinates[1].toDouble()
            }
        } else {
            null
        }
    }
}
